export const MATCH_TIME_ON_REQUEST = "MATCH_TIME_ON_REQUEST";
export const MATCH_TIME_ON_SUCCESS = "MATCH_TIME_ON_SUCCESS";
export const MATCH_TIME_ON_FAIL = "MATCH_TIME_ON_FAIL";

export const CHARTS_REQUEST = "CHARTS_REQUEST";
export const CHARTS_SUCCESS = "CHARTS_SUCCESS";
export const CHARTS_FAIL = "CHARTS_FAIL";

export const STATISTIC_REQUEST = "STATISTIC_REQUEST";
export const STATISTIC_SUCCESS = "STATISTIC_SUCCESS";
export const STATISTIC_FAIL = "STATISTIC_FAIL";

export const NEWS_REQUEST = "NEWS_REQUEST";
export const NEWS_SUCCESS = "NEWS_SUCCESS";
export const NEWS_FAIL = "NEWS_FAIL";

export const ROUND_MATCH_REQUEST = "ROUND_MATCH_REQUEST";
export const ROUND_MATCH_FAIL = "ROUND_MATCH_FAIL";
export const ROUND_MATCH_SUCCESS = "ROUND_MATCH_SUCCESS";

export const INIT_STATE = "INIT_STATE";
export const CLEAR_ERROR = "CLEAR_ERROR";
export const CHANGE_NATION = "CHANGE_NATION";

export const LISTS_VIDEO_REQUEST = "LISTS_VIDEO_REQUEST";
export const LISTS_VIDEO_FAIL = "LISTS_VIDEO_FAIL";
export const LISTS_VIDEO_SUCCESS = "LISTS_VIDEO_SUCCESS";

export const HIGHTLIGHT_REQUEST = " HIGHTLIGHT_REQUEST";
export const HIGHTLIGHT_SUCCESS = " HIGHTLIGHT_SUCCESS";
export const HIGHTLIGHT_FAIL = " HIGHTLIGHT_FAIL";
