export const type = {
    rating: "Đánh giá",
    goals: "Số bàn thắng",
    assists: "Số kiến tạo",
    goalsAssistsSum: "Tổng bàn thắng + kiến tạo",
    penaltyGoals: "Bàn thắng phạt đền",
    freeKickGoal: "Bàn thắng đá phạt",
    scoringFrequency: "Tần suất ghi đểm",
    totalShots: "Tổng cú sút",
    shotsOnTarget: "Sút trúng đích",
    bigChancesMissed: "Cơ hội bỏ lỡ",
    bigChancesCreated: "Cơ hội tạo ra",
    accuratePasses: "Đường truyền chính xác",
    keyPasses: "keyPasses",
    accurateLongBalls: "Truyền dài trúng đích",
    successfulDribbles: "Rê bóng",
    penaltyWon: "Thắng phạt đền",
    tackles: "Tác bóng",
    interceptions: "Cản phá",
    clearances: "Dọn dẹp",
    possessionLost: "Mất bóng",
    yellowCards: "Thẻ vàng",
    redCards: "Thẻ đỏ",
    saves: "Cứu thua",
    mostConceded: "Thủng lưới nhiều nhất mỗi trận",
    leastConceded: "Thủng lưới ít nhất mỗi trận",
    cleanSheet: "Sạch lưới",
};
